version: '3'
services:
  ebook-converter:
    build: .
    container_name: ebook-converter
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
      - ./output:/app/output
    restart: unless-stopped
    environment:
      - NODE_ENV=production