name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Build Docker image
        id: build-image
        continue-on-error: true
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t ebook-converter:latest \
            --load .

      - name: Test Docker image
        if: steps.build-image.outcome == 'success'
        run: |
          docker run -d --name test-container ebook-converter:latest
          sleep 10
          if [ "$(docker inspect -f '{{.State.Running}}' test-container)" = "false" ]; then
            echo "容器启动失败！"
            docker logs test-container
            exit 1
          else
            echo "容器成功启动！"
            docker stop test-container
            docker rm test-container
          fi

      - name: Save Docker image
        if: steps.build-image.outcome == 'success'
        run: |
          mkdir -p artifacts/image
          docker save -o artifacts/image/ebook-converter.tar ebook-converter:latest

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        if: steps.build-image.outcome == 'success'
        with:
          name: docker-image
          path: artifacts/image/ebook-converter.tar
          retention-days: 7

      # 保留原有的日志提取和上传步骤...
