deploy:
  needs: build
  runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Build and push Docker images to ECR
      run: |
        # 构建并推送后端镜像
        docker build -t ${{ secrets.ECR_REPOSITORY }}/book-converter-backend:${{ github.sha }} ./backend
        docker push ${{ secrets.ECR_REPOSITORY }}/book-converter-backend:${{ github.sha }}
        
        # 构建并推送前端镜像
        docker build -t ${{ secrets.ECR_REPOSITORY }}/book-converter-frontend:${{ github.sha }} ./frontend
        docker push ${{ secrets.ECR_REPOSITORY }}/book-converter-frontend:${{ github.sha }}
    
    - name: Deploy to ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: task-definition.json
        service: book-converter-service
        cluster: book-converter-cluster
        wait-for-service-stability: true
