name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: false
          tags: book-converter-backend:latest
      
      - name: Build frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile  # 需要创建frontend/Dockerfile
          push: false
          tags: book-converter-frontend:latest
      
      - name: Test Docker images
        run: |
          # 这里可以添加测试命令，例如启动容器并检查健康状态
          echo "Testing Docker images..."
