name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main  # 推送到main分支时触发

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # 设置超时时间

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('server/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Build Docker image
        run: |
          docker build \
            --cache-from type=local,src=/tmp/.buildx-cache \
            --cache-to type=local,dest=/tmp/.buildx-cache \
            -t ebook-converter:latest .

      - name: Save Docker image
        run: |
          mkdir -p artifacts
          docker save -o artifacts/ebook-converter.tar ebook-converter:latest

      - name: Upload image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: artifacts/ebook-converter.tar
          retention-days: 7  # 保留7天
