name: Build Docker Image

on:
  push:
    branches:
      - main  # 当main分支有更新时触发构建

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and save Docker image
        run: |
          docker build -t ebook-converter:latest .
          mkdir -p artifacts
          docker save -o artifacts/image.tar ebook-converter:latest

      - name: Upload image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: artifacts/image.tar
